var API_URL = 'https://api.forecast.io/forecast/245e43548516a03f6afd16e5bf31af69/';

navigator.geolocation.getCurrentPosition(function(location){
  var lat = location.coords.latitude;
  var long = location.coords.longitude;
  
  getJSONP(API_URL + lat + ',' + long, 'addTempToSpan');
});

var docFragment = document.createDocumentFragment(); 
// generated by hmtl2dom 

var h1 = document.createElement('H1');
docFragment.appendChild(h1);
var text = document.createTextNode("Current Temperature: ");
h1.appendChild(text);

var span = document.createElement('SPAN');
h1.appendChild(span);
var text_0 = document.createTextNode("70");
span.appendChild(text_0);
var text_1 = document.createTextNode("ºF");
h1.appendChild(text_1);

return docFragment;
  
function addTempToSpan(data) {
  debugger;
  var body = document.body;
  var temperature = data.currently.temperature.toFixed(1);
  body.innerHTML = '';
  
  body.appendChild(createWeatherNode(temperature));
  //var span = document.querySelector('span');
  //span.innerHTML = data.currently.temperature.toFixed(1);
}

function getJSONP(url, cb) {
  var script = document.createElement('script');
  script.src = url + '?callback=' + cb;
  
  document.body.appendChild(script);
}
/*function getJSON(url, cb) {
  var xhr = new XMLHttpRequest();

  xhr.open('GET', url);
  xhr.onload = function () {
    if (this.status >= 200 && this.status < 400) {
      cb(JSON.parse(this.response));
    }
  };

  xhr.send();
}*/
